# -*- coding: utf-8 -*-
"""presentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOxrLMPy1ng5UUZ07jp6UaT8e2bw_CNd

NII TO PNG

[link text](https://)# New Section
"""

#  Install and import required libraries
!pip install opencv-python-headless

import os
import cv2
import numpy as np
from google.colab import drive
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt

# === STEP 1: Mount Google Drive ===
drive.mount('/content/drive')

# === STEP 2: Set your input/output paths ===
input_folder = '/content/drive/MyDrive/ms_unet/train/images'     # Folder with FLAIR JPG or PNG images
output_folder = '/content/drive/MyDrive/ms_unet/train/preprocessed'  # Output folder for lesion masks

Path(output_folder).mkdir(parents=True, exist_ok=True)

# === STEP 3: Define lesion detection function ===
def detect_lesions(image):
    # Normalize
    norm_image = cv2.normalize(image, None, 0, 255, cv2.NORM_MINMAX)
    # Blur
    blurred = cv2.GaussianBlur(norm_image, (5, 5), 0)
    # Threshold bright areas
    threshold_value = np.percentile(blurred, 98)
    bright_mask = (blurred >= threshold_value).astype(np.uint8) * 255
    # Clean with morphology
    kernel = np.ones((3, 3), np.uint8)
    bright_mask_clean = cv2.morphologyEx(bright_mask, cv2.MORPH_OPEN, kernel)
    # Connected components
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(bright_mask_clean)
    lesion_mask = np.zeros_like(bright_mask_clean)
    for i in range(1, num_labels):
        if stats[i, cv2.CC_STAT_AREA] > 50:  # Filter small areas
            lesion_mask[labels == i] = 255
    return lesion_mask

# === STEP 4: Process all images in folder ===
for filename in tqdm(os.listdir(input_folder), desc="Processing Images"):
    if filename.lower().endswith(('.jpg', '.png')):
        img_path = os.path.join(input_folder, filename)
        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
            print(f"⚠ Failed to read: {img_path}")
            continue

        lesion_mask = detect_lesions(image)

        # Save result
        out_name = os.path.splitext(filename)[0] + '_lesion_mask.png'
        out_path = os.path.join(output_folder, out_name)
        cv2.imwrite(out_path, lesion_mask)

print("✅ Lesion masks saved to:", output_folder)

"""Pre-Processing"""

!pip install SimpleITK scikit-image

from google.colab import drive
drive.mount('/content/drive')

import os
import SimpleITK as sitk
import numpy as np
from skimage.restoration import denoise_nl_means
from sklearn.preprocessing import MinMaxScaler

# Paths
base_data_path = '/content/drive/MyDrive/msdataset'  # Replace with the path containing your patient folders
output_base_path = '/content/drive/MyDrive/Flair_dataset_/msdataset_jpg'  # New path for saving images

# Create the output directory if it doesn't exist
os.makedirs(output_base_path, exist_ok=True)

# NLM parameters
patch_size = 5
patch_distance = 6
h = 0.08

# Preprocessing loop
for patient_folder in os.listdir(base_data_path):
    patient_path = os.path.join(base_data_path, patient_folder)
    if os.path.isdir(patient_path):
        # Assuming your Flair folders are named Flair1, Flair2, etc.
        flair_folder = f'Flair{len(patient_folder)}'
        flair_path = os.path.join(patient_path, flair_folder)

        if os.path.exists(flair_path):
            # Process each image file within the Flair folder
            for image_file in os.listdir(flair_path):
                if image_file.endswith(('.png', '.jpg', '.jpeg')): # Check for image formats
                    image_path = os.path.join(flair_path, image_file)

                    # Load the image as a SimpleITK image
                    image = sitk.ReadImage(image_path)

                    # Cast the image to sitkFloat32 before applying N4 bias field correction
                    image = sitk.Cast(image, sitk.sitkFloat32)

                    # Extraction (if needed)
                    # ... (Add your extraction code here) ...

                    # Bias correction (N4)
                    corrector = sitk.N4BiasFieldCorrectionImageFilter()
                    corrected_image = corrector.Execute(image)

                    # Denoising (NLM)
                    image_np = sitk.GetArrayFromImage(corrected_image)
                    denoised_image_np = denoise_nl_means(image_np, patch_size=patch_size, patch_distance=patch_distance, h=h)
                    denoised_image = sitk.GetImageFromArray(denoised_image_np)

                    # Normalization (MinMaxScaler)
                    scaler = MinMaxScaler()
                    normalized_image_np = scaler.fit_transform(denoised_image_np.reshape(-1, 1)).reshape(denoised_image_np.shape)

                    # Cast to unsigned char (uint8) and scale to 0-255
                    normalized_image_np_uint8 = (normalized_image_np * 255).astype(np.uint8)

                    # Create a SimpleITK image with the correct pixel type
                    normalized_image_uint8 = sitk.GetImageFromArray(normalized_image_np_uint8)


                    # Save the image (use PNG to avoid data type issues)
                    output_path = os.path.join(output_base_path, f'{patient_folder}_{image_file}')
                    sitk.WriteImage(normalized_image_uint8, output_path.replace('.jpg', '.png'))

                    print(f'Preprocessed Flair image for {patient_folder} saved to {output_path.replace(".jpg", ".png")}')

!pip install SimpleITK scikit-image

from google.colab import drive
drive.mount('/content/drive')

import os
import SimpleITK as sitk
import numpy as np
from skimage.restoration import denoise_nl_means
from sklearn.preprocessing import MinMaxScaler

# Paths
base_data_path = '/content/drive/MyDrive/msdataset'  # Replace with the path containing your patient folders
output_base_path = '/content/drive/MyDrive/Flair_dataset_/msdataset_jpg'  # New path for saving images

# Create the output directory if it doesn't exist
os.makedirs(output_base_path, exist_ok=True)

# NLM parameters
patch_size = 5
patch_distance = 6
h = 0.08

# Preprocessing loop for all 30 patients
for patient_index in range(1, 31):  # Loop for 30 patients
    patient_folder = f'Patient {patient_index}'
    patient_path = os.path.join(base_data_path, patient_folder)

    if os.path.isdir(patient_path):
        # Create Flair folder name dynamically
        flair_folder = f'Flair{patient_index}'
        flair_path = os.path.join(patient_path, flair_folder)

        if os.path.exists(flair_path):
            # Process each image file within the Flair folder
            for image_file in os.listdir(flair_path):
                if image_file.endswith(('.png', '.jpg', '.jpeg')):
                    image_path = os.path.join(flair_path, image_file)

                    # Load the image as a SimpleITK image
                    image = sitk.ReadImage(image_path)

                    # Cast the image to sitkFloat32
                    image = sitk.Cast(image, sitk.sitkFloat32)

                    # Bias correction (N4)
                    corrector = sitk.N4BiasFieldCorrectionImageFilter()
                    corrected_image = corrector.Execute(image)

                    # Denoising (NLM)
                    image_np = sitk.GetArrayFromImage(corrected_image)
                    denoised_image_np = denoise_nl_means(image_np, patch_size=patch_size, patch_distance=patch_distance, h=h)
                    denoised_image = sitk.GetImageFromArray(denoised_image_np)

                    # Normalization (MinMaxScaler)
                    scaler = MinMaxScaler()
                    normalized_image_np = scaler.fit_transform(denoised_image_np.reshape(-1, 1)).reshape(denoised_image_np.shape)

                    # Cast to unsigned char (uint8) and scale to 0-255
                    normalized_image_np_uint8 = (normalized_image_np * 255).astype(np.uint8)

                    # Create a SimpleITK image with the correct pixel type
                    normalized_image_uint8 = sitk.GetImageFromArray(normalized_image_np_uint8)

                    # Save the image (use PNG to avoid data type issues)
                    output_path = os.path.join(output_base_path, f'{patient_folder}_{image_file}')
                    sitk.WriteImage(normalized_image_uint8, output_path.replace('.jpg', '.png'))

                    print(f'Preprocessed Flair image for {patient_folder} saved to {output_path.replace(".jpg", ".png")}')

"""Data Structure"""

# Install dependencies
!pip install opencv-python-headless

import os
import cv2
import numpy as np
from pathlib import Path
from google.colab import drive
from tqdm import tqdm

# Mount Google Drive
drive.mount('/content/drive')

# === CONFIGURATION ===
input_jpg_folder = "/content/drive/MyDrive/no ms flair/BRAINIX_NIFTI_FLAIR"
output_png_folder = "/content/drive/MyDrive/pre no ms"

Path(output_png_folder).mkdir(parents=True, exist_ok=True)

# === FUNCTIONS ===
def normalize_slice(img):
    norm = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX)
    return norm.astype(np.uint8)

def denoise_slice(img):
    return cv2.fastNlMeansDenoising(img, h=10)

def crop_slice(img):
    _, thresh = cv2.threshold(img, 5, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return img
    x, y, w, h = cv2.boundingRect(max(contours, key=cv2.contourArea))
    cropped = img[y:y+h, x:x+w]
    return cv2.resize(cropped, (256, 256))

# === MAIN LOOP ===
for root, dirs, files in os.walk(input_jpg_folder):
    for file in tqdm(files, desc="Processing JPGs"):
        if file.endswith(".jpg"):
            file_path = os.path.join(root, file)
            img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

            if img is None:
                print(f"⚠ Failed to read: {file_path}")
                continue

            img = normalize_slice(img)
            img = denoise_slice(img)
            img = crop_slice(img)

            # Create subfolder structure if needed
            rel_path = os.path.relpath(root, input_jpg_folder)
            out_subfolder = os.path.join(output_png_folder, rel_path)
            Path(out_subfolder).mkdir(parents=True, exist_ok=True)

            out_name = os.path.splitext(file)[0] + ".png"
            out_path = os.path.join(out_subfolder, out_name)

            cv2.imwrite(out_path, img)

print("✅ All JPGs converted to preprocessed PNGs.")

# Install dependencies
!pip install opencv-python-headless

import os
import cv2
import numpy as np
from pathlib import Path
from google.colab import drive
from tqdm import tqdm

# Mount Google Drive
drive.mount('/content/drive')

# === CONFIGURATION ===
input_jpg_folder = "/content/drive/MyDrive/ms_unet/train/images"  # Input folder containing JPG images
output_png_folder = "/content/drive/MyDrive/ms_unet/train/preprocessed"  # Output folder for ALL preprocessed PNG images

# Create output folder if it doesn't exist
Path(output_png_folder).mkdir(parents=True, exist_ok=True)

# === FUNCTIONS ===
def normalize_slice(img):
    norm = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX)
    return norm.astype(np.uint8)

def denoise_slice(img):
    return cv2.fastNlMeansDenoising(img, h=10)

def crop_slice(img):
    _, thresh = cv2.threshold(img, 5, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return img
    x, y, w, h = cv2.boundingRect(max(contours, key=cv2.contourArea))
    cropped = img[y:y+h, x:x+w]
    return cv2.resize(cropped, (256, 256))

# === MAIN LOOP ===
for root, dirs, files in os.walk(input_jpg_folder):
    for file in tqdm(files, desc="Processing JPGs"):
        if file.endswith(".jpg"):
            file_path = os.path.join(root, file)
            img = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

            if img is None:
                print(f"⚠ Failed to read: {file_path}")
                continue

            img = normalize_slice(img)
            img = denoise_slice(img)
            img = crop_slice(img)

            # Construct output filename directly in the output folder
            out_name = os.path.splitext(file)[0] + ".png"
            out_path = os.path.join(output_png_folder, out_name)

            cv2.imwrite(out_path, img)

print("✅ All JPGs converted to preprocessed PNGs and saved in a single folder.")

"""testing and training"""

# === Step 1: Mount Google Drive ===
from google.colab import drive
drive.mount('/content/drive')

# === Step 2: Import Libraries ===
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Conv2DTranspose, concatenate
import matplotlib.pyplot as plt

# === Step 3: Define Paths ===
image_dir = '/content/drive/MyDrive/ms_unet/train/images'  # Replace with your actual path
mask_dir = '/content/drive/MyDrive/ms_unet/train/masks'   # Replace with your actual path

# === Step 4: Load and Preprocess Images and Masks ===
def load_dataset(image_dir, mask_dir, image_size=(256, 256)):
    X = []
    y = []

    image_files = sorted([f for f in os.listdir(image_dir) if f.endswith(('.png', '.jpg'))])

    for img_file in image_files:
        img_path = os.path.join(image_dir, img_file)
        base_name = os.path.splitext(img_file)[0]
        mask_file = base_name + '_lesion_mask_mask.png'  # Adjusted mask filename
        mask_path = os.path.join(mask_dir, mask_file)

        if not os.path.exists(mask_path):
            print(f"Mask not found for: {img_file}, skipping...")
            continue

        # Load and preprocess image
        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        image = cv2.resize(image, image_size)
        image = image / 255.0
        image = np.expand_dims(image, axis=-1)

        # Load and preprocess mask
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.resize(mask, image_size)
        mask = (mask > 127).astype(np.uint8)
        mask = np.expand_dims(mask, axis=-1)

        X.append(image)
        y.append(mask)

    return np.array(X), np.array(y)

X, y = load_dataset(image_dir, mask_dir)

# === Step 5: Train/Test Split ===
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# === Step 6: Define U-Net Model ===
def unet_model(input_size=(256, 256, 1)):
    inputs = Input(input_size)

    # Encoder
    c1 = Conv2D(64, 3, activation='relu', padding='same')(inputs)
    c1 = Conv2D(64, 3, activation='relu', padding='same')(c1)
    p1 = MaxPooling2D((2, 2))(c1)

    c2 = Conv2D(128, 3, activation='relu', padding='same')(p1)
    c2 = Conv2D(128, 3, activation='relu', padding='same')(c2)
    p2 = MaxPooling2D((2, 2))(c2)

    c3 = Conv2D(256, 3, activation='relu', padding='same')(p2)
    c3 = Conv2D(256, 3, activation='relu', padding='same')(c3)
    p3 = MaxPooling2D((2, 2))(c3)

    c4 = Conv2D(512, 3, activation='relu', padding='same')(p3)
    c4 = Conv2D(512, 3, activation='relu', padding='same')(c4)
    p4 = MaxPooling2D((2, 2))(c4)

    # Bottleneck
    c5 = Conv2D(1024, 3, activation='relu', padding='same')(p4)
    c5 = Conv2D(1024, 3, activation='relu', padding='same')(c5)

    # Decoder
    u6 = Conv2DTranspose(512, 2, strides=2, padding='same')(c5)
    u6 = concatenate([u6, c4])
    c6 = Conv2D(512, 3, activation='relu', padding='same')(u6)
    c6 = Conv2D(512, 3, activation='relu', padding='same')(c6)

    u7 = Conv2DTranspose(256, 2, strides=2, padding='same')(c6)
    u7 = concatenate([u7, c3])
    c7 = Conv2D(256, 3, activation='relu', padding='same')(u7)
    c7 = Conv2D(256, 3, activation='relu', padding='same')(c7)

    u8 = Conv2DTranspose(128, 2, strides=2, padding='same')(c7)
    u8 = concatenate([u8, c2])
    c8 = Conv2D(128, 3, activation='relu', padding='same')(u8)
    c8 = Conv2D(128, 3, activation='relu', padding='same')(c8)

    u9 = Conv2DTranspose(64, 2, strides=2, padding='same')(c8)
    u9 = concatenate([u9, c1])
    c9 = Conv2D(64, 3, activation='relu', padding='same')(u9)
    c9 = Conv2D(64, 3, activation='relu', padding='same')(c9)

    outputs = Conv2D(1, 1, activation='sigmoid')(c9)

    model = Model(inputs=[inputs], outputs=[outputs])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

    return model

# === Step 7: Train the Model ===
model = unet_model()
model.fit(X_train, y_train, validation_data=(X_val, y_val), batch_size=8, epochs=10)

# === Step 8: Save the Model ===
model.save('/content/drive/MyDrive/ms_unet_model.h5')

print("✅ Model trained and saved successfully.")

# === Mount Google Drive ===
from google.colab import drive
drive.mount('/content/drive')

# === Imports ===
import h5py
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# === Load Dataset from HDF5 ===
with h5py.File('/content/drive/MyDrive/HDF5 files/ms_lesion_dataset.h5', 'r') as f:
    X = np.array(f['X']) / 255.0
    Y = np.array(f['Y']) / 255.0

print("✅ Loaded dataset:", X.shape)

# === Split into Training and Validation Sets ===
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

# === Basic Augmentation Function (No tf-addons needed) ===
def augment(img, mask):
    img = tf.cast(img, tf.float32)
    mask = tf.cast(mask, tf.float32)

    if tf.random.uniform(()) > 0.5:
        img = tf.image.flip_left_right(img)
        mask = tf.image.flip_left_right(mask)

    if tf.random.uniform(()) > 0.5:
        img = tf.image.flip_up_down(img)
        mask = tf.image.flip_up_down(mask)

    if tf.random.uniform(()) > 0.5:
        img = tf.image.random_brightness(img, max_delta=0.1)

    return img, mask

# === tf.data Pipelines ===
batch_size = 8

train_ds = tf.data.Dataset.from_tensor_slices((X_train, Y_train))
train_ds = train_ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
train_ds = train_ds.shuffle(100).batch(batch_size).prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices((X_val, Y_val))
val_ds = val_ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

# === U-Net Architecture ===
def unet_model(input_size=(256, 256, 1)):
    inputs = tf.keras.Input(input_size)

    # 🟦 Encoding Path
    c1 = tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same')(inputs)
    c1 = tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same')(c1)
    p1 = tf.keras.layers.MaxPooling2D(2)(c1)

    c2 = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same')(p1)
    c2 = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same')(c2)
    p2 = tf.keras.layers.MaxPooling2D(2)(c2)

    c3 = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(p2)
    c3 = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(c3)
    p3 = tf.keras.layers.MaxPooling2D(2)(c3)

    c4 = tf.keras.layers.Conv2D(512, 3, activation='relu', padding='same')(p3)
    c4 = tf.keras.layers.Conv2D(512, 3, activation='relu', padding='same')(c4)
    p4 = tf.keras.layers.MaxPooling2D(2)(c4)

    # 🟧 Bottleneck
    c5 = tf.keras.layers.Conv2D(1024, 3, activation='relu', padding='same')(p4)
    c5 = tf.keras.layers.Conv2D(1024, 3, activation='relu', padding='same')(c5)

    # 🟩 Decoding Path with Skip Connections
    u6 = tf.keras.layers.Conv2DTranspose(512, 2, strides=2, padding='same')(c5)
    u6 = tf.keras.layers.concatenate([u6, c4])
    c6 = tf.keras.layers.Conv2D(512, 3, activation='relu', padding='same')(u6)
    c6 = tf.keras.layers.Conv2D(512, 3, activation='relu', padding='same')(c6)

    u7 = tf.keras.layers.Conv2DTranspose(256, 2, strides=2, padding='same')(c6)
    u7 = tf.keras.layers.concatenate([u7, c3])
    c7 = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(u7)
    c7 = tf.keras.layers.Conv2D(256, 3, activation='relu', padding='same')(c7)

    u8 = tf.keras.layers.Conv2DTranspose(128, 2, strides=2, padding='same')(c7)
    u8 = tf.keras.layers.concatenate([u8, c2])
    c8 = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same')(u8)
    c8 = tf.keras.layers.Conv2D(128, 3, activation='relu', padding='same')(c8)

    u9 = tf.keras.layers.Conv2DTranspose(64, 2, strides=2, padding='same')(c8)
    u9 = tf.keras.layers.concatenate([u9, c1])
    c9 = tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same')(u9)
    c9 = tf.keras.layers.Conv2D(64, 3, activation='relu', padding='same')(c9)

    # 🎯 Output Layer
    outputs = tf.keras.layers.Conv2D(1, 1, activation='sigmoid')(c9)

    model = tf.keras.Model(inputs, outputs)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

# === Train the Model ===
model = unet_model()
history = model.fit(train_ds, validation_data=val_ds, epochs=20)

# === Save Model to Google Drive ===
model.save('/content/drive/MyDrive/unet_ms_lesion_augmented.h5')
print("✅ Model saved to Google Drive.")

# === Plot Training History ===
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title("U-Net Training History")
plt.xlabel("Epoch")
plt.ylabel("Metric Value")
plt.legend()
plt.grid(True)
plt.show()

"""Prediction Masking"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
import random

# === Paths ===
image_dir = '/content/drive/MyDrive/ms_unet/train/images'
mask_dir = '/content/drive/MyDrive/ms_unet/train/masks'
model_path = '/content/drive/MyDrive/ms_unet_model.h5'

# === Load and preprocess dataset ===
def load_dataset(image_dir, mask_dir, image_size=(256, 256)):
    X, y, orig_images = [], [], []

    image_files = sorted([f for f in os.listdir(image_dir) if f.endswith(('.png', '.jpg'))])

    for img_file in image_files:
        img_path = os.path.join(image_dir, img_file)
        base_name = os.path.splitext(img_file)[0]
        mask_file = base_name + '_lesion_mask_mask.png'
        mask_path = os.path.join(mask_dir, mask_file)

        if not os.path.exists(mask_path):
            continue

        img_orig = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        orig_images.append(img_orig.copy())

        img = cv2.resize(img_orig, image_size) / 255.0
        img = np.expand_dims(img, axis=-1)

        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.resize(mask, image_size)
        mask = (mask > 127).astype(np.uint8)
        mask = np.expand_dims(mask, axis=-1)

        X.append(img)
        y.append(mask)

    return np.array(X), np.array(y), orig_images

# Load data
X, y, original_images = load_dataset(image_dir, mask_dir)
X_train, X_val, y_train, y_val, orig_train, orig_val = train_test_split(X, y, original_images, test_size=0.2, random_state=42)

# Load model
model = load_model(model_path)

# Predict and visualize with bounding boxes (show all even small spots)
num_samples = 5
indices = random.sample(range(len(X_val)), num_samples)

for i, idx in enumerate(indices):
    img = X_val[idx]
    original_img = orig_val[idx]
    h, w = original_img.shape

    pred_mask = model.predict(np.expand_dims(img, axis=0))[0]
    pred_mask_thresh = (pred_mask > 0.5).astype(np.uint8).squeeze()

    # Resize predicted mask to original image size
    resized_pred_mask = cv2.resize(pred_mask_thresh, (w, h), interpolation=cv2.INTER_NEAREST)

    # Find contours (including very small ones)
    contours, _ = cv2.findContours(resized_pred_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    boxed_img = cv2.cvtColor(original_img, cv2.COLOR_GRAY2BGR)

    for cnt in contours:
        x, y, bw, bh = cv2.boundingRect(cnt)

        # Filter only outer-edge contours (optional)
        margin = 5
        if x <= margin or y <= margin or x + bw >= w - margin or y + bh >= h - margin:
            continue

        cv2.rectangle(boxed_img, (x, y), (x + bw, y + bh), (0, 255, 0), 2)

    # Display original + boxes and predicted mask
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(boxed_img)
    plt.title('Original with Bounding Boxes')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(resized_pred_mask, cmap='gray')
    plt.title('Predicted Mask')
    plt.axis('off')

    plt.tight_layout()
    plt.show()

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
import random

# === Paths ===
image_dir = '/content/drive/MyDrive/ms_unet/train/images'
mask_dir = '/content/drive/MyDrive/ms_unet/train/masks'
model_path = '/content/drive/MyDrive/ms_unet_model.h5'

# === Load and preprocess dataset ===
def load_dataset(image_dir, mask_dir, image_size=(256, 256)):
    X, y, orig_images = [], [], []

    image_files = sorted([f for f in os.listdir(image_dir) if f.endswith(('.png', '.jpg'))])

    for img_file in image_files:
        img_path = os.path.join(image_dir, img_file)
        base_name = os.path.splitext(img_file)[0]
        mask_file = base_name + '_lesion_mask_mask.png'
        mask_path = os.path.join(mask_dir, mask_file)

        if not os.path.exists(mask_path):
            continue

        img_orig = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        orig_images.append(img_orig.copy())

        img = cv2.resize(img_orig, image_size) / 255.0
        img = np.expand_dims(img, axis=-1)

        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = cv2.resize(mask, image_size)
        mask = (mask > 127).astype(np.uint8)
        mask = np.expand_dims(mask, axis=-1)

        X.append(img)
        y.append(mask)

    return np.array(X), np.array(y), orig_images

# Load data
X, y, original_images = load_dataset(image_dir, mask_dir)
X_train, X_val, y_train, y_val, orig_train, orig_val = train_test_split(X, y, original_images, test_size=0.2, random_state=42)

# Load model
model = load_model(model_path)

# === Highlight Lesions and Uneven High-Intensity Spots ===
num_samples = 5
indices = random.sample(range(len(X_val)), num_samples)

for i, idx in enumerate(indices):
    img = X_val[idx]
    original_img = orig_val[idx]
    h, w = original_img.shape

    # Enhance contrast
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced_img = clahe.apply(original_img)

    # Predict from model
    pred_mask = model.predict(np.expand_dims(img, axis=0))[0]
    pred_mask = (pred_mask > 0.45).astype(np.uint8).squeeze()
    resized_pred = cv2.resize(pred_mask, (w, h), interpolation=cv2.INTER_NEAREST)

    # Extract central region
    cx1, cx2 = w // 4, 3 * w // 4
    cy1, cy2 = h // 4, 3 * h // 4
    central_crop = enhanced_img[cy1:cy2, cx1:cx2]

    # Adaptive threshold to detect localized bright spots
    central_thresh = cv2.adaptiveThreshold(central_crop, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
                                           cv2.THRESH_BINARY, 15, -5)

    # Filter small uneven regions using connected components
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(central_thresh)

    filtered_spots = np.zeros_like(central_thresh)
    for i in range(1, num_labels):
        area = stats[i, cv2.CC_STAT_AREA]
        if 10 <= area <= 150:  # Keeps small bright regions, removes large or noise
            filtered_spots[labels == i] = 255

    # Place filtered center spots back into full mask
    central_mask = np.zeros_like(resized_pred, dtype=np.uint8)
    central_mask[cy1:cy2, cx1:cx2] = filtered_spots

    # Combine with U-Net prediction
    final_mask = np.logical_or(resized_pred, (central_mask > 0)).astype(np.uint8)

    # Draw boxes on original image
    contours, _ = cv2.findContours(final_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    boxed_img = cv2.cvtColor(original_img, cv2.COLOR_GRAY2BGR)

    margin = 5
    for cnt in contours:
        x, y, bw, bh = cv2.boundingRect(cnt)
        if x <= margin or y <= margin or x + bw >= w - margin or y + bh >= h - margin:
            continue
        cv2.rectangle(boxed_img, (x, y), (x + bw, y + bh), (0, 255, 0), 2)

    # Display
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(boxed_img)
    plt.title('Spots & Lesions Highlighted')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(final_mask, cmap='gray')
    plt.title('Final Binary Mask')
    plt.axis('off')
    plt.tight_layout()
    plt.show()

from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
import random

# === Pick a random validation image ===
index = random.randint(0, len(X_val) - 1)
sample_image = X_val[index]
original_image = (sample_image.squeeze() * 255).astype(np.uint8)

# === Create a feature extractor from selected U-Net layers ===
layer_names = ['conv2d', 'conv2d_2', 'conv2d_6', 'conv2d_10', 'conv2d_14']  # adjust layer names if needed
outputs = [model.get_layer(name).output for name in layer_names]
feature_model = Model(inputs=model.input, outputs=outputs)

# === Get feature maps ===
feature_maps = feature_model.predict(np.expand_dims(sample_image, axis=0))

# === Predict segmentation ===
pred_mask = model.predict(np.expand_dims(sample_image, axis=0))[0].squeeze()
binary_mask = (pred_mask > 0.45).astype(np.uint8)

# === Plot Feature Maps ===
plt.figure(figsize=(18, 6))
plt.subplot(1, len(layer_names) + 2, 1)
plt.imshow(original_image, cmap='gray')
plt.title("Original")
plt.axis('off')

for i, fmap in enumerate(feature_maps):
    fmap_img = fmap[0, :, :, 0]  # visualize only first channel
    plt.subplot(1, len(layer_names) + 2, i + 2)
    plt.imshow(fmap_img, cmap='viridis')
    plt.title(f"Layer {i+1}")
    plt.axis('off')

plt.subplot(1, len(layer_names) + 2, len(layer_names) + 2)
plt.imshow(binary_mask, cmap='gray')
plt.title("Predicted Mask")
plt.axis('off')
plt.tight_layout()
plt.show()

"""MOdel Summary"""

from tensorflow.keras.models import load_model

# Load the model from .h5 file
model = load_model("/content/drive/MyDrive/ms_unet_model.h5")  # Replace with your actual file path

# Print the model summary
model.summary()

"""Model Architecture as PNG"""

from tensorflow.keras.utils import plot_model

# Save model architecture as a PNG image
plot_model(model, to_file='unet_model.png', show_shapes=True, show_layer_names=True)

import numpy as np
from tensorflow.keras.models import load_model

# === Load Test Data (replace with your actual test image and mask paths) ===
image_dir = "/content/drive/MyDrive/ms_unet/test/images"
mask_dir = "/content/drive/MyDrive/ms_unet/test/masks"

def load_images(img_dir, mask_dir):
    import os, cv2
    X, y = [], []
    for img_file in os.listdir(img_dir):
        if img_file.endswith('.png'):
            img_path = os.path.join(img_dir, img_file)
            mask_path = os.path.join(mask_dir, img_file.replace('.png', '_lesion_mask_mask.png'))
            if os.path.exists(mask_path):
                img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                img = cv2.resize(img, (256, 256))
                mask = cv2.resize(mask, (256, 256))
                X.append(img)
                y.append(mask)
    X = np.expand_dims(np.array(X), -1) / 255.0
    y = np.expand_dims((np.array(y) > 127).astype(np.uint8), -1)
    return X, y

X_test, y_test = load_images(image_dir, mask_dir)

# === Load trained U-Net model ===
model = load_model('/content/drive/MyDrive/ms_unet_model.h5')

# === Predict on test set ===
y_pred = model.predict(X_test)

# === Prepare for evaluation ===
y_true_flat = y_test.flatten()
y_pred_flat = (y_pred > 0.5).astype(np.uint8).flatten()
y_prob_flat = y_pred.flatten()  # For PR and ROC curves

"""Precision-Recall Curve"""

import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve, average_precision_score

precision, recall, _ = precision_recall_curve(y_true_flat, y_prob_flat)
ap = average_precision_score(y_true_flat, y_prob_flat)

plt.figure(figsize=(8, 6))
plt.plot(recall, precision, label=f'AP = {ap:.4f}')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curve')
plt.legend()
plt.grid(True)
plt.show()

"""ROC Curve"""

from sklearn.metrics import roc_curve, roc_auc_score

fpr, tpr, _ = roc_curve(y_true_flat, y_prob_flat)
auc = roc_auc_score(y_true_flat, y_prob_flat)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'AUC = {auc:.4f}')
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid(True)
plt.show()

"""Confusion Matrix

"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_true_flat, y_pred_flat)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(6, 5))
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap='Blues', xticklabels=['No Lesion', 'Lesion'], yticklabels=['No Lesion', 'Lesion'])
plt.title('Normalized Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""Trainig and Testing Effiency"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, precision_recall_curve, confusion_matrix, ConfusionMatrixDisplay
import torch

# === Mount Google Drive ===
from google.colab import drive
drive.mount('/content/drive')

# === Imports ===
import h5py
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

# === Load Dataset from HDF5 File ===
dataset_path = '/content/drive/MyDrive/HDF5 files/ms_lesion_dataset.h5'
with h5py.File(dataset_path, 'r') as f:
    X = np.array(f['X']) / 255.0  # normalize to [0, 1]
    Y = np.array(f['Y']) / 255.0

print(f"✅ Loaded dataset: X={X.shape}, Y={Y.shape}")

# === 80/20 Train-Test Split (same as in training) ===
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

# === Load Trained Model ===
model_path = '/content/drive/MyDrive/HDF5 files/unet_ms_lesion_augmented.h5'
model = tf.keras.models.load_model(model_path)
print("✅ Loaded trained U-Net model.")

# === Evaluate Accuracy ===
train_loss, train_acc = model.evaluate(X_train, Y_train, verbose=0)
val_loss, val_acc = model.evaluate(X_val, Y_val, verbose=0)

# === Display Accuracy as Percentage ===
print(f"📊 Training Accuracy   : {train_acc * 100:.2f}%")
print(f"📊 Validation Accuracy : {val_acc * 100:.2f}%")